const C3  = ['red', 'blue', 'yellow'];
const C4  = ['red', 'blue', 'yellow', 'green'];
const C5  = ['red', 'blue', 'yellow', 'green', 'purple'];
const C6  = ['red', 'blue', 'yellow', 'green', 'purple', 'orange'];
const C7  = ['red', 'blue', 'yellow', 'green', 'purple', 'orange', 'cyan'];
const C8  = ['red', 'blue', 'yellow', 'green', 'purple', 'orange', 'cyan', 'pink'];
const C9  = ['red', 'blue', 'yellow', 'green', 'purple', 'orange', 'cyan', 'pink', 'lime'];
const C10 = ['red', 'blue', 'yellow', 'green', 'purple', 'orange', 'cyan', 'pink', 'lime', 'maroon'];

export const ZONE_DEFS = [
    { id: 1, name: 'Awakening', emoji: '🌅', accent: '#4a90e2', bg: 'linear-gradient(to bottom, #0d1b2a, #1a3052)' },
    { id: 2, name: 'Chill',     emoji: '❄️',  accent: '#48d4c9', bg: 'linear-gradient(to bottom, #0a2a2a, #1a4040)' },
    { id: 3, name: 'Heat',      emoji: '🔥',  accent: '#f5a623', bg: 'linear-gradient(to bottom, #2a1200, #4a2200)' },
    { id: 4, name: 'Haunt',     emoji: '👻',  accent: '#9b59b6', bg: 'linear-gradient(to bottom, #1a0a2e, #2d1458)' },
    { id: 5, name: 'Inferno',   emoji: '💀',  accent: '#e74c3c', bg: 'linear-gradient(to bottom, #1a0000, #3a0000)' },
];

export const STORY_LEVELS = [
    // ─── Zone 1: Awakening ────────────────────────────────────────────────────
    {
        id: 1, zone: 1, boss: false,
        title: 'First Steps',
        flavour: 'A gentle beginning. Three colours, two pegs. You\'ve got this.',
        seed: 'story-level-1',
        coinsReward: 20,
        config: { codeLength: 2, maxGuesses: 12, colors: C3 },
        modifiers: [],
    },
    {
        id: 2, zone: 1, boss: false,
        title: 'Colour Blind',
        flavour: 'Four colours now. Don\'t overthink it.',
        seed: 'story-level-2',
        coinsReward: 20,
        config: { codeLength: 2, maxGuesses: 10, colors: C4 },
        modifiers: [],
    },
    {
        id: 3, zone: 1, boss: false,
        title: 'Third Wheel',
        flavour: 'Three pegs enter the chat.',
        seed: 'story-level-3',
        coinsReward: 20,
        config: { codeLength: 3, maxGuesses: 10, colors: C3 },
        modifiers: [],
    },
    {
        id: 4, zone: 1, boss: false,
        title: 'Four Play',
        flavour: 'Three pegs, four colours. Still manageable.',
        seed: 'story-level-4',
        coinsReward: 20,
        config: { codeLength: 3, maxGuesses: 10, colors: C4 },
        modifiers: [],
    },
    {
        id: 5, zone: 1, boss: false,
        title: 'Expanding Palette',
        flavour: 'Five colours to choose from. Your logic skills are growing.',
        seed: 'story-level-5',
        coinsReward: 20,
        config: { codeLength: 3, maxGuesses: 8, colors: C5 },
        modifiers: [],
    },
    {
        id: 6, zone: 1, boss: false,
        title: 'Six Shot',
        flavour: 'Six colours, still only three pegs. The combinations multiply.',
        seed: 'story-level-6',
        coinsReward: 20,
        config: { codeLength: 3, maxGuesses: 8, colors: C6 },
        modifiers: [],
    },
    {
        id: 7, zone: 1, boss: false,
        title: 'Classic-ish',
        flavour: 'Four pegs now. Welcome to the big leagues.',
        seed: 'story-level-7',
        coinsReward: 20,
        config: { codeLength: 4, maxGuesses: 8, colors: C5 },
        modifiers: [],
    },
    {
        id: 8, zone: 1, boss: false,
        title: 'Getting Serious',
        flavour: 'Six colours, four pegs. This is what real Mastermind feels like.',
        seed: 'story-level-8',
        coinsReward: 20,
        config: { codeLength: 4, maxGuesses: 8, colors: C6 },
        modifiers: [],
    },
    {
        id: 9, zone: 1, boss: false,
        title: 'Lucky Seven',
        flavour: 'Seven colours in the mix. Stay systematic.',
        seed: 'story-level-9',
        coinsReward: 20,
        config: { codeLength: 4, maxGuesses: 7, colors: C7 },
        modifiers: [],
    },
    {
        id: 10, zone: 1, boss: true,
        title: 'The Awakening',
        flavour: 'Eight colours. Four pegs. Eight guesses. The full classic experience — and your first real test.',
        seed: 'story-level-10',
        coinsReward: 50,
        config: { codeLength: 4, maxGuesses: 8, colors: C8 },
        modifiers: [],
    },

    // ─── Zone 2: Chill ────────────────────────────────────────────────────────
    {
        id: 11, zone: 2, boss: false,
        title: 'Cold Shoulder',
        flavour: 'One slot is frozen. You won\'t see its feedback — deduce it from the others.',
        seed: 'story-level-11',
        coinsReward: 25,
        config: { codeLength: 4, maxGuesses: 8, colors: C6 },
        modifiers: [{ type: 'freeze', slots: [0] }],
    },
    {
        id: 12, zone: 2, boss: false,
        title: 'Blind Side',
        flavour: 'The last slot is iced over. What\'s hiding in position four?',
        seed: 'story-level-12',
        coinsReward: 25,
        config: { codeLength: 4, maxGuesses: 8, colors: C6 },
        modifiers: [{ type: 'freeze', slots: [3] }],
    },
    {
        id: 13, zone: 2, boss: false,
        title: 'Ice Age',
        flavour: 'Seven colours now, and one slot still frozen. Cold logic required.',
        seed: 'story-level-13',
        coinsReward: 25,
        config: { codeLength: 4, maxGuesses: 8, colors: C7 },
        modifiers: [{ type: 'freeze', slots: [1] }],
    },
    {
        id: 14, zone: 2, boss: false,
        title: 'Locked In',
        flavour: 'Whatever you place in position one on your first guess sticks forever. Choose carefully.',
        seed: 'story-level-14',
        coinsReward: 25,
        config: { codeLength: 4, maxGuesses: 8, colors: C6 },
        modifiers: [{ type: 'lock', slots: [0] }],
    },
    {
        id: 15, zone: 2, boss: false,
        title: 'Set In Stone',
        flavour: 'Position three is committed. No take-backs once you\'ve guessed.',
        seed: 'story-level-15',
        coinsReward: 25,
        config: { codeLength: 4, maxGuesses: 8, colors: C6 },
        modifiers: [{ type: 'lock', slots: [2] }],
    },
    {
        id: 16, zone: 2, boss: false,
        title: 'No Take-Backs',
        flavour: 'Seven colours, and whatever you put in position two is yours forever.',
        seed: 'story-level-16',
        coinsReward: 25,
        config: { codeLength: 4, maxGuesses: 7, colors: C7 },
        modifiers: [{ type: 'lock', slots: [1] }],
    },
    {
        id: 17, zone: 2, boss: false,
        title: 'Frozen Over',
        flavour: 'One slot frozen, one locked. Half the board is compromised.',
        seed: 'story-level-17',
        coinsReward: 25,
        config: { codeLength: 4, maxGuesses: 7, colors: C7 },
        modifiers: [{ type: 'freeze', slots: [2] }, { type: 'lock', slots: [0] }],
    },
    {
        id: 18, zone: 2, boss: false,
        title: 'Arctic',
        flavour: 'Eight colours. One frozen clue, one locked commitment. Welcome to the tundra.',
        seed: 'story-level-18',
        coinsReward: 25,
        config: { codeLength: 4, maxGuesses: 7, colors: C8 },
        modifiers: [{ type: 'freeze', slots: [1] }, { type: 'lock', slots: [3] }],
    },
    {
        id: 19, zone: 2, boss: false,
        title: 'Deep Freeze',
        flavour: 'Two slots frozen. You\'re working with half the information.',
        seed: 'story-level-19',
        coinsReward: 25,
        config: { codeLength: 4, maxGuesses: 7, colors: C8 },
        modifiers: [{ type: 'freeze', slots: [0, 2] }],
    },
    {
        id: 20, zone: 2, boss: true,
        title: 'The Glacier',
        flavour: 'One frozen slot. Two locked slots. Eight colours. Seven guesses. The ice claims its own.',
        seed: 'story-level-20',
        coinsReward: 60,
        config: { codeLength: 4, maxGuesses: 7, colors: C8 },
        modifiers: [{ type: 'freeze', slots: [1] }, { type: 'lock', slots: [0, 2] }],
    },

    // ─── Zone 3: Heat ─────────────────────────────────────────────────────────
    {
        id: 21, zone: 3, boss: false,
        title: 'Tick Tock',
        flavour: 'A bomb on position four. You have 3 guesses to place the right colour there — or it goes off.',
        seed: 'story-level-21',
        coinsReward: 30,
        config: { codeLength: 4, maxGuesses: 8, colors: C6 },
        modifiers: [{ type: 'bomb', slots: [3], fuseGuesses: 3, penalty: 'loseGuesses', penaltyAmount: 2 }],
    },
    {
        id: 22, zone: 3, boss: false,
        title: 'Live Wire',
        flavour: 'Position two is armed. Four guesses before the fuse burns out.',
        seed: 'story-level-22',
        coinsReward: 30,
        config: { codeLength: 4, maxGuesses: 8, colors: C7 },
        modifiers: [{ type: 'bomb', slots: [1], fuseGuesses: 4, penalty: 'loseGuesses', penaltyAmount: 2 }],
    },
    {
        id: 23, zone: 3, boss: false,
        title: 'Hot Seat',
        flavour: 'Position one is ticking. Don\'t wait too long.',
        seed: 'story-level-23',
        coinsReward: 30,
        config: { codeLength: 4, maxGuesses: 8, colors: C7 },
        modifiers: [{ type: 'bomb', slots: [0], fuseGuesses: 3, penalty: 'loseGuesses', penaltyAmount: 2 }],
    },
    {
        id: 24, zone: 3, boss: false,
        title: 'Smoke and Mirrors',
        flavour: 'Position three has a mirror. Black clues show as white, white as black — for that slot only.',
        seed: 'story-level-24',
        coinsReward: 30,
        config: { codeLength: 4, maxGuesses: 8, colors: C6 },
        modifiers: [{ type: 'mirror', slots: [2] }],
    },
    {
        id: 25, zone: 3, boss: false,
        title: 'Reflection',
        flavour: 'Position one is mirrored. Your instincts will lie to you.',
        seed: 'story-level-25',
        coinsReward: 30,
        config: { codeLength: 4, maxGuesses: 8, colors: C7 },
        modifiers: [{ type: 'mirror', slots: [0] }],
    },
    {
        id: 26, zone: 3, boss: false,
        title: 'Flip Side',
        flavour: 'Eight colours, seven guesses, and position four tells you lies.',
        seed: 'story-level-26',
        coinsReward: 30,
        config: { codeLength: 4, maxGuesses: 7, colors: C8 },
        modifiers: [{ type: 'mirror', slots: [3] }],
    },
    {
        id: 27, zone: 3, boss: false,
        title: 'Trick Shot',
        flavour: 'A bomb on position three and a mirror on position two. Tread carefully.',
        seed: 'story-level-27',
        coinsReward: 30,
        config: { codeLength: 4, maxGuesses: 8, colors: C7 },
        modifiers: [
            { type: 'bomb', slots: [2], fuseGuesses: 3, penalty: 'loseGuesses', penaltyAmount: 2 },
            { type: 'mirror', slots: [1] },
        ],
    },
    {
        id: 28, zone: 3, boss: false,
        title: 'House of Cards',
        flavour: 'Bomb on position one, mirror on position four. One false move collapses everything.',
        seed: 'story-level-28',
        coinsReward: 30,
        config: { codeLength: 4, maxGuesses: 7, colors: C8 },
        modifiers: [
            { type: 'bomb', slots: [0], fuseGuesses: 4, penalty: 'loseGuesses', penaltyAmount: 2 },
            { type: 'mirror', slots: [3] },
        ],
    },
    {
        id: 29, zone: 3, boss: false,
        title: 'Double Trouble',
        flavour: 'Two bombs. Two fuses. Both counting down. Prioritise.',
        seed: 'story-level-29',
        coinsReward: 30,
        config: { codeLength: 4, maxGuesses: 7, colors: C8 },
        modifiers: [{ type: 'bomb', slots: [1, 3], fuseGuesses: 3, penalty: 'loseGuesses', penaltyAmount: 2 }],
    },
    {
        id: 30, zone: 3, boss: true,
        title: 'Inferno Protocol',
        flavour: 'Bombs on positions one and three. A mirror on position two. Six guesses. This is not a drill.',
        seed: 'story-level-30',
        coinsReward: 75,
        config: { codeLength: 4, maxGuesses: 6, colors: C8 },
        modifiers: [
            { type: 'bomb', slots: [0, 2], fuseGuesses: 3, penalty: 'loseGuesses', penaltyAmount: 2 },
            { type: 'mirror', slots: [1] },
        ],
    },

    // ─── Zone 4: Haunt ────────────────────────────────────────────────────────
    {
        id: 31, zone: 4, boss: false,
        title: 'The Haunting',
        flavour: 'Position one is haunted. Every 3 guesses its colour silently shifts. You won\'t be warned.',
        seed: 'story-level-31',
        coinsReward: 35,
        config: { codeLength: 4, maxGuesses: 8, colors: C8 },
        modifiers: [{ type: 'ghost', slots: [0], shiftEvery: 3 }],
    },
    {
        id: 32, zone: 4, boss: false,
        title: 'Moving Target',
        flavour: 'Position four shifts every 3 rows. What you knew is now wrong.',
        seed: 'story-level-32',
        coinsReward: 35,
        config: { codeLength: 4, maxGuesses: 7, colors: C8 },
        modifiers: [{ type: 'ghost', slots: [3], shiftEvery: 3 }],
    },
    {
        id: 33, zone: 4, boss: false,
        title: 'Restless',
        flavour: 'Position two shifts every 2 guesses. Fast and relentless.',
        seed: 'story-level-33',
        coinsReward: 35,
        config: { codeLength: 4, maxGuesses: 7, colors: C8 },
        modifiers: [{ type: 'ghost', slots: [1], shiftEvery: 2 }],
    },
    {
        id: 34, zone: 4, boss: false,
        title: 'Fog of War',
        flavour: 'Smoke fills the board. All clue feedback is delayed by one row.',
        seed: 'story-level-34',
        coinsReward: 35,
        config: { codeLength: 4, maxGuesses: 8, colors: C8 },
        modifiers: [{ type: 'smoke' }],
    },
    {
        id: 35, zone: 4, boss: false,
        title: 'Blackout',
        flavour: 'Five pegs, smoke delay. More positions. Less clarity.',
        seed: 'story-level-35',
        coinsReward: 35,
        config: { codeLength: 5, maxGuesses: 8, colors: C8 },
        modifiers: [{ type: 'smoke' }],
    },
    {
        id: 36, zone: 4, boss: false,
        title: 'Cold Ghost',
        flavour: 'A ghost on position three and a frozen slot at five. Two unknowns, one logical path.',
        seed: 'story-level-36',
        coinsReward: 35,
        config: { codeLength: 5, maxGuesses: 8, colors: C8 },
        modifiers: [{ type: 'ghost', slots: [2], shiftEvery: 3 }, { type: 'freeze', slots: [4] }],
    },
    {
        id: 37, zone: 4, boss: false,
        title: 'Ghost in the Machine',
        flavour: 'A ghost shifting every 2 guesses, wrapped in smoke. Stay sharp.',
        seed: 'story-level-37',
        coinsReward: 35,
        config: { codeLength: 5, maxGuesses: 7, colors: C8 },
        modifiers: [{ type: 'ghost', slots: [0], shiftEvery: 2 }, { type: 'smoke' }],
    },
    {
        id: 38, zone: 4, boss: false,
        title: 'Blinded',
        flavour: 'Smoke and a locked slot. Whatever you commit to position two, you\'re committed.',
        seed: 'story-level-38',
        coinsReward: 35,
        config: { codeLength: 5, maxGuesses: 7, colors: C9 },
        modifiers: [{ type: 'smoke' }, { type: 'lock', slots: [1] }],
    },
    {
        id: 39, zone: 4, boss: false,
        title: 'Two Ghosts',
        flavour: 'Two haunted positions. Both shifting every 3 guesses. Both lying about what they are.',
        seed: 'story-level-39',
        coinsReward: 35,
        config: { codeLength: 5, maxGuesses: 7, colors: C9 },
        modifiers: [{ type: 'ghost', slots: [1, 3], shiftEvery: 3 }],
    },
    {
        id: 40, zone: 4, boss: true,
        title: 'The Haunted Circuit',
        flavour: 'Ghost on position one (shifts every 2), smoke delay, frozen position four. Nine colours. Six guesses.',
        seed: 'story-level-40',
        coinsReward: 90,
        config: { codeLength: 5, maxGuesses: 6, colors: C9 },
        modifiers: [
            { type: 'ghost', slots: [0], shiftEvery: 2 },
            { type: 'smoke' },
            { type: 'freeze', slots: [3] },
        ],
    },

    // ─── Zone 5: Inferno ──────────────────────────────────────────────────────
    {
        id: 41, zone: 5, boss: false,
        title: 'Bomb Chaser',
        flavour: 'A bomb on position three, a ghost on position five shifting every 3. The clock and the code both betray you.',
        seed: 'story-level-41',
        coinsReward: 50,
        config: { codeLength: 5, maxGuesses: 7, colors: C9 },
        modifiers: [
            { type: 'bomb', slots: [2], fuseGuesses: 3, penalty: 'loseGuesses', penaltyAmount: 2 },
            { type: 'ghost', slots: [4], shiftEvery: 3 },
        ],
    },
    {
        id: 42, zone: 5, boss: false,
        title: 'Mirror Fog',
        flavour: 'Position one lies to you with mirrors. The smoke makes it worse.',
        seed: 'story-level-42',
        coinsReward: 50,
        config: { codeLength: 5, maxGuesses: 7, colors: C9 },
        modifiers: [{ type: 'mirror', slots: [0] }, { type: 'smoke' }],
    },
    {
        id: 43, zone: 5, boss: false,
        title: 'Phantom Lock',
        flavour: 'A ghost shifting every 2 and a locked position three. Commit and adapt.',
        seed: 'story-level-43',
        coinsReward: 50,
        config: { codeLength: 5, maxGuesses: 7, colors: C9 },
        modifiers: [{ type: 'ghost', slots: [0], shiftEvery: 2 }, { type: 'lock', slots: [2] }],
    },
    {
        id: 44, zone: 5, boss: false,
        title: 'Arctic Bomb',
        flavour: 'Two frozen positions, one bomb. Ten colours. Six guesses. The ice wants you to fail.',
        seed: 'story-level-44',
        coinsReward: 50,
        config: { codeLength: 5, maxGuesses: 6, colors: C10 },
        modifiers: [
            { type: 'freeze', slots: [1, 3] },
            { type: 'bomb', slots: [4], fuseGuesses: 3, penalty: 'loseGuesses', penaltyAmount: 2 },
        ],
    },
    {
        id: 45, zone: 5, boss: false,
        title: 'Halls of Illusion',
        flavour: 'A mirror on position three, a ghost on position five, and smoke throughout. Nothing is as it seems.',
        seed: 'story-level-45',
        coinsReward: 50,
        config: { codeLength: 5, maxGuesses: 6, colors: C10 },
        modifiers: [
            { type: 'mirror', slots: [2] },
            { type: 'ghost', slots: [4], shiftEvery: 3 },
            { type: 'smoke' },
        ],
    },
    {
        id: 46, zone: 5, boss: false,
        title: 'Triple Threat',
        flavour: 'Bomb. Mirror. Lock. Position one ticks. Position four deceives. Position three commits.',
        seed: 'story-level-46',
        coinsReward: 50,
        config: { codeLength: 5, maxGuesses: 6, colors: C10 },
        modifiers: [
            { type: 'bomb', slots: [0], fuseGuesses: 3, penalty: 'loseGuesses', penaltyAmount: 2 },
            { type: 'mirror', slots: [3] },
            { type: 'lock', slots: [2] },
        ],
    },
    {
        id: 47, zone: 5, boss: false,
        title: 'Phantasm',
        flavour: 'Six pegs. Smoke delay. Frozen position three. Ghost on position six shifting every 3.',
        seed: 'story-level-47',
        coinsReward: 50,
        config: { codeLength: 6, maxGuesses: 7, colors: C9 },
        modifiers: [
            { type: 'smoke' },
            { type: 'freeze', slots: [2] },
            { type: 'ghost', slots: [5], shiftEvery: 3 },
        ],
    },
    {
        id: 48, zone: 5, boss: false,
        title: "Witch's Brew",
        flavour: 'A bomb on position four, a mirror on position one, and smoke. Six pegs. Brew carefully.',
        seed: 'story-level-48',
        coinsReward: 50,
        config: { codeLength: 6, maxGuesses: 7, colors: C10 },
        modifiers: [
            { type: 'bomb', slots: [3], fuseGuesses: 3, penalty: 'loseGuesses', penaltyAmount: 2 },
            { type: 'mirror', slots: [0] },
            { type: 'smoke' },
        ],
    },
    {
        id: 49, zone: 5, boss: false,
        title: 'The Long Game',
        flavour: 'Two ghosts shifting every 2. A frozen position. A locked commitment. Six pegs. Ten colours.',
        seed: 'story-level-49',
        coinsReward: 50,
        config: { codeLength: 6, maxGuesses: 6, colors: C10 },
        modifiers: [
            { type: 'ghost', slots: [0, 3], shiftEvery: 2 },
            { type: 'freeze', slots: [5] },
            { type: 'lock', slots: [2] },
        ],
    },
    {
        id: 50, zone: 5, boss: true,
        title: 'The Inferno Engine',
        flavour: 'A bomb. A ghost. A frozen slot. A mirror. Smoke. Six pegs. Ten colours. Six guesses. This is the end.',
        seed: 'story-level-50',
        coinsReward: 150,
        config: { codeLength: 6, maxGuesses: 6, colors: C10 },
        modifiers: [
            { type: 'bomb', slots: [2], fuseGuesses: 3, penalty: 'loseGuesses', penaltyAmount: 2 },
            { type: 'ghost', slots: [0], shiftEvery: 2 },
            { type: 'freeze', slots: [4] },
            { type: 'mirror', slots: [5] },
            { type: 'smoke' },
        ],
    },
];

export const MODIFIER_META = {
    freeze: { emoji: '❄️', label: 'Freeze',  desc: 'Feedback for this slot is hidden.' },
    lock:   { emoji: '🔒', label: 'Lock',    desc: 'Your first guess in this slot is permanent.' },
    bomb:   { emoji: '💣', label: 'Bomb',    desc: 'Place the right colour before the fuse runs out.' },
    mirror: { emoji: '🪞', label: 'Mirror',  desc: 'Black and white feedback are inverted for this slot.' },
    ghost:  { emoji: '👻', label: 'Ghost',   desc: 'The colour in this slot silently shifts every N guesses.' },
    smoke:  { emoji: '💨', label: 'Smoke',   desc: 'All row feedback is delayed by one row.' },
};
